apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-cred
  namespace: demo
spec:

  # Mount path of the secrets backend
  mount: database

  allowStaticCreds: true
  # Path to the secret
  path: static-creds/my-static-role

  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: db-secret

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
    - kind: Deployment
      name: my-app

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-auth
